### ISSUE TITLE
'wc-product-tables' is not a registered wp command

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-product-tables-feature-plugin#121]
I'm testing it on my staging site and got this error. What should I do?

> wp wc-product-tables migrate-data --clean-old-data

> Error: 'wc-product-tables' is not a registered wp command. See 'wp help' for available commands.

**Comment by rodrigoprimo** [comment]
@kevin25, is the plugin active? Usually, when the command is not registered it is because the plugin is deactivated.

**Comment by kevin25** [comment]
@rodrigoprimo  of course it was active.

**Comment by rodrigoprimo** [comment]
I asked if the plugin was active because this is the most common cause for errors like this. I can confirm that you are trying to run the right command and it should work. I'm not sure if there is anything else I can do to help. Do you happen to have access to another environment where you could test if the plugin or at least test if the plugin is able to register the WP-CLI command? You could run `wp wc-product-tables migrate-data --help` to test if the command is registered without any side effects.

**Comment by hereswhatidid** [comment]
I"m also getting this same error and have confirmed the plugin is installed. I'm using the Local by Flywheel environment if that helps narrow it down.

**Comment by claudiosanches** [comment]
I'm not able to reproduce this issue, maybe missing WP-CLI, or maybe the plugin deactivated, but I can confirm that is running on master and with WooCommerce 3.7.
