### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by premiumlion** [woocommerce/woocommerce-product-tables-feature-plugin#137]
This seems like a REALLY important performance update. 

No updates since November 1st of 2018?

Really looking forward to this.

Thank you.

**Comment by wss-chadical** [comment]
+1

**Comment by tonybahama** [comment]
Same question here :)

**Comment by rusowyler** [comment]
+1

**Comment by wss-chadical** [comment]
Actually, just a project update in general would be great. I can understand that dates can be difficult to nail down.

**Comment by spoyntersmith** [comment]
+1

**Comment by n1smo** [comment]
+1

**Comment by tonybahama** [comment]
that is right. Also including the fact that many large stores suffer from performance problem, and this development has been going on for 1 year now.

**Comment by VivekManglani** [comment]
This is extremely important for WC to implement into core.

**Comment by stephansperling** [comment]
+1

**Comment by kevin25** [comment]
+1 Can't wait for that.

**Comment by ufo56** [comment]
+1

**Comment by lightsoutdave** [comment]
+1

**Comment by ronakganatra9** [comment]
+1

**Comment by matteobaro** [comment]
+1

**Comment by jchrislemmer** [comment]
+1 - would love to know what the update is on this? We don't want to implement Beta software on live! This is a great plugin and we cannot wait!

**Comment by kevin25** [comment]
I've been waiting for this plugin for almost a month. This will be one of the most important and useful features ever. Please make it live.

**Comment by nh** [comment]
+1

**Comment by dynit** [comment]
+1 , seems to be a necessary update for scaling/performance

**Comment by costa974** [comment]
+1

**Comment by sharperedge** [comment]
+1 we could really use an update

**Comment by fransing** [comment]
+1

**Comment by peterfabian** [comment]
Hi all,
we have been focusing on performance improvements for past couple of months and tried to identify the biggest bottlenecks and areas where we could add the most value without breaking backwards compatibility. As you all know, adding a custom table for products not only breaks backwards compatibility, but also brings other challenges in terms of extensibility, etc. That is why we currently don't have a timeline when custom product tables will land in core. However, we are shipping various performance improvements in 3.6 that should be released mid April and we hope it will help a lot of users.
I hope this brings a bit of background to the lack of updates seen in this repository.

**Comment by matteobaro** [comment]
> Hi all,
> we have been focusing on performance improvements for past couple of months and tried to identify the biggest bottlenecks and areas where we could add the most value without breaking backwards compatibility. As you all know, adding a custom table for products not only breaks backwards compatibility, but also brings other challenges in terms of extensibility, etc. That is why we currently don't have a timeline when custom product tables will land in core. However, we are shipping various performance improvements in 3.6 that should be released mid April and we hope it will help a lot of users.
> I hope this brings a bit of background to the lack of updates seen in this repository.

please continue to develop this function as external plugin for advanced users

**Comment by lukecav** [comment]
Any idea on when any WP-CLI existing product migration commands will be added into the plugin?

**Comment by kevin25** [comment]
Well it’s already added

**Comment by lukecav** [comment]
@kevin25 
I did not notice /includes/class-wc-product-tables-cli.php
The main readme file does not mention anything about the WP-CLI commands or the supported options.

**Comment by vasikgreif** [comment]
@peterfabian Thabks for the update, but there's no way you can solve the performance issues for stores with large number of products or orders without using custom tables for the data. I do support for quite some big stores, with billions of rows in the postmeta table. There's no way around that, the DB structure is simply wrong for large amount of data.

Please, release this as a plugin for advanced users. I don't care about backward compatibility, if some plugin won't work with this, I can write my own etc.

To make our customers happy, we need custom tables for orders and products. There's simply no way around that.

**Comment by imnamanmodi1** [comment]
@vasikgreif I agree with your point totally, recenty one of my client moved his large store from Woo to Shopify because woocommerce was slow with his large number of data.

**Comment by lukecav** [comment]
@vasikgreif
How many products and orders on that site before it was moved over to Shopify from WooCommerce?

**Comment by vasikgreif** [comment]
@lukecav Well, I still was able to conceive my customers to stay with WooCommerce, as I promised them WooCommerce will have the custom data tables plugin ready this year (it was planned for last year on the Trello board). 

Frankly, everyone knows that WooCommerce sucks with many orders or products, mostly because of getting the data from huge postmeta table takes ages. The DB structure is not designed for large amounts of data, and I pointed away many potential customers from WooCommerce, as I know large stores simply won't work well in the current DB state. Basically, it's "You have a small business? WooCommerce is cool for you. Have you bigger plans? Stay away".

**Comment by imnamanmodi1** [comment]
@lukecav it was around more then 75k+ products (includes variations) & with each having atleast 3-4 images,  db sucked literally & site was so slow, Rest Api endpoints returnes data very slow & eventually webapp was slower.

**Comment by glagonikas** [comment]
@peterfabian @mikejolley appreciate the majority of WooCommerce stores are tiny, small or medium sized and they are the ones making money for Automattic but at this stage, it seems like you're kicking the can down the road regarding the custom tables causing ongoing grief to large sites and thoughts of leaving (or not using WC in the first place).

This has been discussed for years and even though other plugins (WPML, Yoast to name a few) use their own custom tables, WC is still stuck in the default WP tables.

I do understand this will be a big change, but i'm not convinced you have real figures on the amount of people who anticipate this change or would benefit from it.

If your problem is with resources (highly doubt it) you could crowdfund this, or simply built it as an official WC plugin. I'm sure large businesses (ourselves included) would gladly pay for this.

**Comment by Fencer04** [comment]
I second the notion of paying for it. I know my clients would definitely
shell out for this feature.

Justin Hansen

**Comment by sharperedge** [comment]
I agree totally. It makes so much sense to move to custom tables. Happy to forego backwards compatibility with some plugins. Any larger installation will have a dev and/or staging site to test these things out. Our clients would definitely pay for this, too.

**Comment by wss-chadical** [comment]
Pantheon customers using Wordpress and Woocommerce would readily welcome this feature set.

We are a medium sized stored (4,000 products), though our order volume is low compared to other storefronts ( < 10k orders per year). So, we are getting close to hitting performance issues for sure - but have some runway. 

We fully support this endeavor, and would be willing to pay as well.

**Comment by andrewlreeve** [comment]
Agree with the comments here - we are a larger Woo store (5000 products with 300,000 orders).

We're already using the Custom Order Tables (from Liquidweb/ Mindsize) and happy to support any compatibility issues in-house. We're also encouraging our engineers to feedback to the community on any fixes if they arise.

Woocommerce needs an enterprise community for stores with in house engineers. We can pool resources and maintain and release "enterprise" solutions.

**Comment by lukecav** [comment]
@andrewlreeve 
Have seen the custom orders table plugin used on stores with 200k, 400k and 1.4+ million orders on them.

**Comment by vasikgreif** [comment]
@peterfabian @mikejolley Any comment from the Woocomerce crew, please? We really need to know what to tell our customers, who are having major performance issues for too long time... 🙄

**Comment by claudiosanches** [comment]
Closing this thread since we are working on it, and I hope to see you'll testing and giving feedback.
I should post a new beta version soon.

**Comment by miculgigant** [comment]
This is actually a much needed update. I kept searching for discussions on how to scale Woocommerce to 1 million products, which are plenty out there. But when I've looked at the DB structure, this thing is not an e-commerce store destined to shops with more than 1.000 or 10.000 products if you really push it. It's just a little plugin where you can sell a bunch of T-shirts from your blog. It's just such a "basic" step forward that would improve things so much. Would also help filtering, which is another big downside of Woocommerce that also needs a solid built-in solution. I found this while looking at ways to improve the DB structure for an app with more than a million entries, when I realized it's just not possible on such a thing. Anyways, me and probably a huge amount of other developers that couldn't find this like I did would really love such a development. Thanks! :)

**Comment by claudiosanches** [comment]
@miculgigant I'm working on it, currently trying to fix some bugs and fix some performance issues.

**Comment by miculgigant** [comment]
@claudiosanches Everyone understands, but it's been a while and this is really needed at this point in time. Do you have any idea of a reliable ETA for this ? You should also know your efforts are much appreciated. Thank you!

**Comment by claudiosanches** [comment]
@miculgigant NO ETA yet, I don't want to promise anything until I'm comfortable with this project, when this felling change I'll announce here.

**Comment by miculgigant** [comment]
@claudiosanches Ah, so, just better to be looking for other solution to build a large scale app and forget about Woocommerce. I really think this piece needs more resources allocated to it, rather than the 1000's of minor little things that are "improved" with each new update, that don't bring any evident change or improved performance. Still makes no sense, but good luck with it.

**Comment by claudiosanches** [comment]
@miculgigant sorry, but this kind of pressure or comment isn't nice, this doesn't add anything on this thread or project.
I'll close this thread for new comments since we can't keep a nice productive conversation.

**Comment by claudiosanches** [comment]
Let me explain for anyone that may come to this thread.

> This seems like a REALLY important performance update.

As per the first comment on this thread we can feel all the exceptions, of course the intent of this project may create exceptions like that "seems like" or "sounds like" a definitive solution, but it's not.
This the only solution, not even is the best solution for all stores, maybe we'll finish it and merge into core and most of the stores see no big performance improvement, even more because performance issues will depend in the whole ecosystem where you WordPress site is installed, also the plugins and theme you are using.

Not to mention that this isn't the only performance improvement that we are currently working on, take for example Product Lookup tables that we implemented this year in WooCommerce 3.6, I ensure everyone, we are working in performance issues and taking it serious.

But again, moving products to custom tables may not be the solution for everyone, so I ask for everyone to please moderate your expectations until we finish our work on it and proper evaluate if it will really help everyone.
